name: ssh_rdp
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  ffi: ^2.1.3
  format: ^1.5.2
  logging: ^1.2.0
  path: ^1.9.0
  stack_trace: ^1.11.1
  win32: ^5.5.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
